#!/usr/bin/env bash

set -Eeuo pipefail

YIOPS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
YIOPS_ENV_FILE="$YIOPS_ROOT/.env.docker"
YIOPS_MODE_FILE="$YIOPS_ROOT/.runtime/service-mode"
YIOPS_ACTION="${1:-up}"

compose_command() {
    if docker compose version >/dev/null 2>&1; then
        YIOPS_COMPOSE=(docker compose)
    elif command -v docker-compose >/dev/null 2>&1; then
        YIOPS_COMPOSE=(docker-compose)
    else
        echo "Docker Compose is required (Docker Compose v2 is recommended)." >&2
        exit 1
    fi
}

random_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 24
    else
        od -An -N24 -tx1 /dev/urandom | tr -d ' \n'
    fi
}

create_env_file() {
    if [[ ! -f "$YIOPS_ENV_FILE" ]]; then
        local mysql_password mysql_root_password
        mysql_password="$(random_secret)"
        mysql_root_password="$(random_secret)"
        umask 077
        printf '%s\n' \
            '# Generated by ./deploy.sh. Keep this file private.' \
            'COMPOSE_PROJECT_NAME=yiops' \
            'MYSQL_IMAGE=mysql:8.4' \
            'YIOPS_IMAGE=yiops:local' \
            'MYSQL_DATABASE=yiops' \
            'MYSQL_USER=yiops' \
            "MYSQL_PASSWORD=$mysql_password" \
            "MYSQL_ROOT_PASSWORD=$mysql_root_password" \
            'YIOPS_BIND_ADDRESS=0.0.0.0' \
            'YIOPS_PORT=8100' \
            'TZ=UTC' \
            'YIOPS_DATASOURCE_MOCK_MODE=false' \
            'YIOPS_LLM_MOCK_MODE=true' \
            'YIOPS_ANALYSIS_CONCURRENCY=2' \
            'YIOPS_ANALYSIS_TIMEOUT_SECONDS=300' \
            'YIOPS_DATASOURCE_TIMEOUT_SECONDS=15' \
            > "$YIOPS_ENV_FILE"
        echo "Created .env.docker with random database passwords."
    fi

    if ! awk -F= '$1 == "YIOPS_AUTH_ENABLED" {found=1} END {exit !found}' "$YIOPS_ENV_FILE"; then
        local admin_password
        admin_password="$(random_secret)"
        printf '%s\n' \
            'YIOPS_AUTH_ENABLED=true' \
            'YIOPS_ADMIN_USERNAME=admin' \
            "YIOPS_ADMIN_PASSWORD=$admin_password" \
            'YIOPS_SESSION_TTL_HOURS=168' \
            'YIOPS_AUTH_COOKIE_SECURE=false' \
            >> "$YIOPS_ENV_FILE"
        echo "Enabled authentication and generated an administrator password."
    fi
}

compose() {
    "${YIOPS_COMPOSE[@]}" --env-file "$YIOPS_ENV_FILE" "$@"
}

setting() {
    local key="$1"
    awk -F= -v wanted="$key" '$1 == wanted {sub(/^[^=]*=/, ""); print; exit}' "$YIOPS_ENV_FILE"
}

wait_until_ready() {
    local container_id health attempt
    container_id="$(compose ps -q yiops)"
    if [[ -z "$container_id" ]]; then
        echo "YiOps container was not created." >&2
        return 1
    fi

    echo "Waiting for YiOps readiness..."
    for attempt in {1..60}; do
        health="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id" 2>/dev/null || true)"
        case "$health" in
            healthy)
                return 0
                ;;
            unhealthy|exited|dead)
                echo "YiOps failed to become ready (status: $health)." >&2
                compose logs --tail=100 yiops >&2
                return 1
                ;;
        esac
        sleep 2
    done

    echo "Timed out waiting for YiOps readiness." >&2
    compose logs --tail=100 yiops >&2
    return 1
}

show_access_url() {
    local port bind_address
    port="$(setting YIOPS_PORT)"
    bind_address="$(setting YIOPS_BIND_ADDRESS)"
    port="${port:-8100}"
    bind_address="${bind_address:-0.0.0.0}"

    echo
    echo "YiOps is ready."
    echo "Web:     http://127.0.0.1:${port}/"
    if [[ "$bind_address" == "0.0.0.0" ]]; then
        echo "LAN:     http://<server-ip>:${port}/"
    fi
    echo "OpenAPI: http://127.0.0.1:${port}/docs"
    echo "Admin:   $(setting YIOPS_ADMIN_USERNAME)"
    echo "Password is stored as YIOPS_ADMIN_PASSWORD in .env.docker."
    echo "Config:  $YIOPS_ENV_FILE"
}

compose_command
cd "$YIOPS_ROOT"

case "$YIOPS_ACTION" in
    up|start)
        create_env_file
        if ! docker info >/dev/null 2>&1; then
            echo "Cannot connect to Docker. Start Docker and ensure the current user can access it." >&2
            exit 1
        fi
        compose up -d --build --remove-orphans
        wait_until_ready
        mkdir -p "$YIOPS_ROOT/.runtime"
        printf 'compose\n' > "$YIOPS_MODE_FILE"
        show_access_url
        ;;
    down|stop)
        create_env_file
        compose down
        echo "YiOps stopped. Persistent volumes were kept."
        ;;
    restart)
        create_env_file
        compose up -d --build --remove-orphans
        wait_until_ready
        show_access_url
        ;;
    status|ps)
        create_env_file
        compose ps
        ;;
    logs)
        create_env_file
        compose logs -f --tail=200 yiops
        ;;
    config)
        create_env_file
        compose config
        ;;
    *)
        echo "Usage: $0 {up|down|restart|status|logs|config}" >&2
        exit 1
        ;;
esac
